2019-10-23 12:47:22 INFO org.hibernate.jpa.internal.util.LogHelper HHH000204: Processing PersistenceUnitInfo [
	name: myJpa
	...] 31
2019-10-23 12:47:23 INFO org.hibernate.Version HHH000412: Hibernate Core {5.4.0.Final} 46
2019-10-23 12:47:23 INFO org.hibernate.cfg.Environment HHH000206: hibernate.properties not found 199
2019-10-23 12:47:23 INFO org.hibernate.annotations.common.reflection.java.JavaReflectionManager HCANN000001: Hibernate Commons Annotations {5.1.0.Final} 49
2019-10-23 12:47:24 INFO org.hibernate.c3p0.internal.C3P0ConnectionProvider HHH010002: C3P0 using driver: com.mysql.jdbc.Driver at URL: jdbc:mysql://localhost:3306/jpa 116
2019-10-23 12:47:24 INFO org.hibernate.c3p0.internal.C3P0ConnectionProvider HHH10001001: Connection properties: {user=root, password=****} 117
2019-10-23 12:47:24 INFO org.hibernate.c3p0.internal.C3P0ConnectionProvider HHH10001003: Autocommit mode: false 120
2019-10-23 12:47:24 INFO com.mchange.v2.log.MLog$1 MLog clients using log4j logging. 124
2019-10-23 12:47:24 INFO com.mchange.v2.c3p0.C3P0Registry Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10] 248
2019-10-23 12:47:24 INFO org.hibernate.c3p0.internal.C3P0ConnectionProvider HHH10001007: JDBC isolation level: <unknown> 200
2019-10-23 12:47:24 INFO com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource Initializing c3p0 pool... com.mchange.v2.c3p0.PoolBackedDataSource@5fdc2bcf [ connectionPoolDataSource -> com.mchange.v2.c3p0.WrapperConnectionPoolDataSource@970f7cc [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, debugUnreturnedConnectionStackTraces -> false, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, identityToken -> 1hgegw1a51wimgvykiz1w5|72035809, idleConnectionTestPeriod -> 0, initialPoolSize -> 3, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, nestedDataSource -> com.mchange.v2.c3p0.DriverManagerDataSource@9af0dfa0 [ description -> null, driverClass -> null, factoryClassLocation -> null, forceUseNamedDriverClass -> false, identityToken -> 1hgegw1a51wimgvykiz1w5|534a5a98, jdbcUrl -> jdbc:mysql://localhost:3306/jpa, properties -> {user=******, password=******} ], preferredTestQuery -> null, privilegeSpawnedThreads -> false, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, usesTraditionalReflectiveProxies -> false; userOverrides: {} ], dataSourceName -> null, extensions -> {}, factoryClassLocation -> null, identityToken -> 1hgegw1a51wimgvykiz1w5|4681c175, numHelperThreads -> 3 ] 527
2019-10-23 12:47:55 WARN com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@50493ef0 -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (30). Last acquisition attempt exception:  1911
java.sql.SQLException: Unknown character set index for field '255' received from server.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:910)
	at com.mysql.jdbc.Connection.getCharsetNameForIndex(Connection.java:3448)
	at com.mysql.jdbc.Field.<init>(Field.java:191)
	at com.mysql.jdbc.MysqlIO.unpackField(MysqlIO.java:659)
	at com.mysql.jdbc.MysqlIO.getResultSet(MysqlIO.java:382)
	at com.mysql.jdbc.MysqlIO.readResultsForQueryOrUpdate(MysqlIO.java:1970)
	at com.mysql.jdbc.MysqlIO.readAllResults(MysqlIO.java:1387)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1727)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3170)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3099)
	at com.mysql.jdbc.Statement.executeQuery(Statement.java:1169)
	at com.mysql.jdbc.Connection.loadServerVariables(Connection.java:4317)
	at com.mysql.jdbc.Connection.initializePropsFromServer(Connection.java:3936)
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2683)
	at com.mysql.jdbc.Connection.<init>(Connection.java:1531)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:266)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1138)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1125)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
	at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1870)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
2019-10-23 12:47:55 WARN com.mchange.v2.resourcepool.BasicResourcePool Having failed to acquire a resource, com.mchange.v2.resourcepool.BasicResourcePool@239a307b is interrupting all Threads waiting on a resource to check out. Will try again in response to new client requests. 946
2019-10-23 12:47:55 WARN org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator HHH000342: Could not obtain connection to query metadata : Connections could not be acquired from the underlying database! 132
2019-10-23 13:16:14 INFO org.hibernate.jpa.internal.util.LogHelper HHH000204: Processing PersistenceUnitInfo [
	name: myJpa
	...] 31
2019-10-23 13:16:15 INFO org.hibernate.Version HHH000412: Hibernate Core {5.4.0.Final} 46
2019-10-23 13:16:15 INFO org.hibernate.cfg.Environment HHH000206: hibernate.properties not found 199
2019-10-23 13:16:17 INFO org.hibernate.annotations.common.reflection.java.JavaReflectionManager HCANN000001: Hibernate Commons Annotations {5.1.0.Final} 49
2019-10-23 13:16:18 INFO org.hibernate.c3p0.internal.C3P0ConnectionProvider HHH010002: C3P0 using driver: com.mysql.jdbc.Driver at URL: jdbc:mysql://localhost:3306/jpa 116
2019-10-23 13:16:18 INFO org.hibernate.c3p0.internal.C3P0ConnectionProvider HHH10001001: Connection properties: {user=root, password=****} 117
2019-10-23 13:16:18 INFO org.hibernate.c3p0.internal.C3P0ConnectionProvider HHH10001003: Autocommit mode: false 120
2019-10-23 13:16:19 INFO com.mchange.v2.log.MLog$1 MLog clients using log4j logging. 124
2019-10-23 13:16:20 INFO com.mchange.v2.c3p0.C3P0Registry Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10] 248
2019-10-23 13:16:20 INFO org.hibernate.c3p0.internal.C3P0ConnectionProvider HHH10001007: JDBC isolation level: <unknown> 200
2019-10-23 13:16:20 INFO com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource Initializing c3p0 pool... com.mchange.v2.c3p0.PoolBackedDataSource@e20ee322 [ connectionPoolDataSource -> com.mchange.v2.c3p0.WrapperConnectionPoolDataSource@11536131 [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, debugUnreturnedConnectionStackTraces -> false, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, identityToken -> 1hgegw1a51wjno60vff56e|5dda6f9, idleConnectionTestPeriod -> 0, initialPoolSize -> 3, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, nestedDataSource -> com.mchange.v2.c3p0.DriverManagerDataSource@4768c412 [ description -> null, driverClass -> null, factoryClassLocation -> null, forceUseNamedDriverClass -> false, identityToken -> 1hgegw1a51wjno60vff56e|11acdc30, jdbcUrl -> jdbc:mysql://localhost:3306/jpa, properties -> {user=******, password=******} ], preferredTestQuery -> null, privilegeSpawnedThreads -> false, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, usesTraditionalReflectiveProxies -> false; userOverrides: {} ], dataSourceName -> null, extensions -> {}, factoryClassLocation -> null, identityToken -> 1hgegw1a51wjno60vff56e|21a5fd96, numHelperThreads -> 3 ] 527
2019-10-23 13:16:52 WARN com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@de09424 -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (30). Last acquisition attempt exception:  1911
java.sql.SQLException: Unknown character set index for field '255' received from server.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:910)
	at com.mysql.jdbc.Connection.getCharsetNameForIndex(Connection.java:3448)
	at com.mysql.jdbc.Field.<init>(Field.java:191)
	at com.mysql.jdbc.MysqlIO.unpackField(MysqlIO.java:659)
	at com.mysql.jdbc.MysqlIO.getResultSet(MysqlIO.java:382)
	at com.mysql.jdbc.MysqlIO.readResultsForQueryOrUpdate(MysqlIO.java:1970)
	at com.mysql.jdbc.MysqlIO.readAllResults(MysqlIO.java:1387)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1727)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3170)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3099)
	at com.mysql.jdbc.Statement.executeQuery(Statement.java:1169)
	at com.mysql.jdbc.Connection.loadServerVariables(Connection.java:4317)
	at com.mysql.jdbc.Connection.initializePropsFromServer(Connection.java:3936)
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2683)
	at com.mysql.jdbc.Connection.<init>(Connection.java:1531)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:266)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1138)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1125)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
	at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1870)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
2019-10-23 13:16:52 WARN com.mchange.v2.resourcepool.BasicResourcePool Having failed to acquire a resource, com.mchange.v2.resourcepool.BasicResourcePool@7db0565c is interrupting all Threads waiting on a resource to check out. Will try again in response to new client requests. 946
2019-10-23 13:16:52 WARN com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@3f2cbaca -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (30). Last acquisition attempt exception:  1911
java.sql.SQLException: Unknown character set index for field '255' received from server.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:910)
	at com.mysql.jdbc.Connection.getCharsetNameForIndex(Connection.java:3448)
	at com.mysql.jdbc.Field.<init>(Field.java:191)
	at com.mysql.jdbc.MysqlIO.unpackField(MysqlIO.java:659)
	at com.mysql.jdbc.MysqlIO.getResultSet(MysqlIO.java:382)
	at com.mysql.jdbc.MysqlIO.readResultsForQueryOrUpdate(MysqlIO.java:1970)
	at com.mysql.jdbc.MysqlIO.readAllResults(MysqlIO.java:1387)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1727)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3170)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3099)
	at com.mysql.jdbc.Statement.executeQuery(Statement.java:1169)
	at com.mysql.jdbc.Connection.loadServerVariables(Connection.java:4317)
	at com.mysql.jdbc.Connection.initializePropsFromServer(Connection.java:3936)
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2683)
	at com.mysql.jdbc.Connection.<init>(Connection.java:1531)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:266)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1138)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1125)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
	at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1870)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
2019-10-23 13:16:52 WARN com.mchange.v2.resourcepool.BasicResourcePool Having failed to acquire a resource, com.mchange.v2.resourcepool.BasicResourcePool@7db0565c is interrupting all Threads waiting on a resource to check out. Will try again in response to new client requests. 946
2019-10-23 13:16:52 WARN com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@6e2a173d -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (30). Last acquisition attempt exception:  1911
java.sql.SQLException: Unknown character set index for field '255' received from server.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:910)
	at com.mysql.jdbc.Connection.getCharsetNameForIndex(Connection.java:3448)
	at com.mysql.jdbc.Field.<init>(Field.java:191)
	at com.mysql.jdbc.MysqlIO.unpackField(MysqlIO.java:659)
	at com.mysql.jdbc.MysqlIO.getResultSet(MysqlIO.java:382)
	at com.mysql.jdbc.MysqlIO.readResultsForQueryOrUpdate(MysqlIO.java:1970)
	at com.mysql.jdbc.MysqlIO.readAllResults(MysqlIO.java:1387)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1727)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3170)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3099)
	at com.mysql.jdbc.Statement.executeQuery(Statement.java:1169)
	at com.mysql.jdbc.Connection.loadServerVariables(Connection.java:4317)
	at com.mysql.jdbc.Connection.initializePropsFromServer(Connection.java:3936)
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2683)
	at com.mysql.jdbc.Connection.<init>(Connection.java:1531)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:266)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1138)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1125)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
	at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1870)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
2019-10-23 13:16:52 WARN com.mchange.v2.resourcepool.BasicResourcePool Having failed to acquire a resource, com.mchange.v2.resourcepool.BasicResourcePool@7db0565c is interrupting all Threads waiting on a resource to check out. Will try again in response to new client requests. 946
2019-10-23 13:16:52 WARN org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator HHH000342: Could not obtain connection to query metadata : Connections could not be acquired from the underlying database! 132
2019-10-23 13:19:17 INFO org.hibernate.jpa.internal.util.LogHelper HHH000204: Processing PersistenceUnitInfo [
	name: myJpa
	...] 31
2019-10-23 13:19:18 INFO org.hibernate.Version HHH000412: Hibernate Core {5.4.0.Final} 46
2019-10-23 13:19:18 INFO org.hibernate.cfg.Environment HHH000206: hibernate.properties not found 199
2019-10-23 13:19:18 INFO org.hibernate.annotations.common.reflection.java.JavaReflectionManager HCANN000001: Hibernate Commons Annotations {5.1.0.Final} 49
2019-10-23 13:19:19 INFO org.hibernate.c3p0.internal.C3P0ConnectionProvider HHH010002: C3P0 using driver: com.mysql.jdbc.Driver at URL: jdbc:mysql://localhost:3306/jpa 116
2019-10-23 13:19:19 INFO org.hibernate.c3p0.internal.C3P0ConnectionProvider HHH10001001: Connection properties: {user=root, password=****} 117
2019-10-23 13:19:19 INFO org.hibernate.c3p0.internal.C3P0ConnectionProvider HHH10001003: Autocommit mode: false 120
2019-10-23 13:19:19 INFO com.mchange.v2.log.MLog$1 MLog clients using log4j logging. 124
2019-10-23 13:19:19 INFO com.mchange.v2.c3p0.C3P0Registry Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10] 248
2019-10-23 13:19:19 INFO org.hibernate.c3p0.internal.C3P0ConnectionProvider HHH10001007: JDBC isolation level: <unknown> 200
2019-10-23 13:19:19 INFO com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource Initializing c3p0 pool... com.mchange.v2.c3p0.PoolBackedDataSource@5b434af3 [ connectionPoolDataSource -> com.mchange.v2.c3p0.WrapperConnectionPoolDataSource@4d816f0 [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, debugUnreturnedConnectionStackTraces -> false, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, identityToken -> 1hgegw1a51wjrii29zimwe|72035809, idleConnectionTestPeriod -> 0, initialPoolSize -> 3, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, nestedDataSource -> com.mchange.v2.c3p0.DriverManagerDataSource@9657fec4 [ description -> null, driverClass -> null, factoryClassLocation -> null, forceUseNamedDriverClass -> false, identityToken -> 1hgegw1a51wjrii29zimwe|534a5a98, jdbcUrl -> jdbc:mysql://localhost:3306/jpa, properties -> {user=******, password=******} ], preferredTestQuery -> null, privilegeSpawnedThreads -> false, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, usesTraditionalReflectiveProxies -> false; userOverrides: {} ], dataSourceName -> null, extensions -> {}, factoryClassLocation -> null, identityToken -> 1hgegw1a51wjrii29zimwe|4681c175, numHelperThreads -> 3 ] 527
2019-10-23 13:19:49 WARN com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@539430ce -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (30). Last acquisition attempt exception:  1911
java.sql.SQLException: Unknown character set index for field '255' received from server.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:910)
	at com.mysql.jdbc.Connection.getCharsetNameForIndex(Connection.java:3448)
	at com.mysql.jdbc.Field.<init>(Field.java:191)
	at com.mysql.jdbc.MysqlIO.unpackField(MysqlIO.java:659)
	at com.mysql.jdbc.MysqlIO.getResultSet(MysqlIO.java:382)
	at com.mysql.jdbc.MysqlIO.readResultsForQueryOrUpdate(MysqlIO.java:1970)
	at com.mysql.jdbc.MysqlIO.readAllResults(MysqlIO.java:1387)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1727)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3170)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3099)
	at com.mysql.jdbc.Statement.executeQuery(Statement.java:1169)
	at com.mysql.jdbc.Connection.loadServerVariables(Connection.java:4317)
	at com.mysql.jdbc.Connection.initializePropsFromServer(Connection.java:3936)
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2683)
	at com.mysql.jdbc.Connection.<init>(Connection.java:1531)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:266)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1138)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1125)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
	at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1870)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
2019-10-23 13:19:49 WARN com.mchange.v2.resourcepool.BasicResourcePool Having failed to acquire a resource, com.mchange.v2.resourcepool.BasicResourcePool@239a307b is interrupting all Threads waiting on a resource to check out. Will try again in response to new client requests. 946
2019-10-23 13:19:49 WARN org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator HHH000342: Could not obtain connection to query metadata : Connections could not be acquired from the underlying database! 132
2019-10-23 13:21:59 INFO org.hibernate.jpa.internal.util.LogHelper HHH000204: Processing PersistenceUnitInfo [
	name: myJpa
	...] 31
2019-10-23 13:22:00 INFO org.hibernate.Version HHH000412: Hibernate Core {5.4.0.Final} 46
2019-10-23 13:22:00 INFO org.hibernate.cfg.Environment HHH000206: hibernate.properties not found 199
2019-10-23 13:22:00 INFO org.hibernate.annotations.common.reflection.java.JavaReflectionManager HCANN000001: Hibernate Commons Annotations {5.1.0.Final} 49
2019-10-23 13:22:01 INFO org.hibernate.c3p0.internal.C3P0ConnectionProvider HHH010002: C3P0 using driver: com.mysql.jdbc.Driver at URL: jdbc:mysql://localhost:3306/jpa 116
2019-10-23 13:22:01 INFO org.hibernate.c3p0.internal.C3P0ConnectionProvider HHH10001001: Connection properties: {user=root, password=****} 117
2019-10-23 13:22:01 INFO org.hibernate.c3p0.internal.C3P0ConnectionProvider HHH10001003: Autocommit mode: false 120
2019-10-23 13:22:01 INFO com.mchange.v2.log.MLog$1 MLog clients using log4j logging. 124
2019-10-23 13:22:02 INFO com.mchange.v2.c3p0.C3P0Registry Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10] 248
2019-10-23 13:22:02 INFO org.hibernate.c3p0.internal.C3P0ConnectionProvider HHH10001007: JDBC isolation level: <unknown> 200
2019-10-23 13:22:02 INFO com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource Initializing c3p0 pool... com.mchange.v2.c3p0.PoolBackedDataSource@5c128b40 [ connectionPoolDataSource -> com.mchange.v2.c3p0.WrapperConnectionPoolDataSource@364b3d53 [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, debugUnreturnedConnectionStackTraces -> false, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, identityToken -> 1hgegw1a51wjuzuf1yrleln|5dda6f9, idleConnectionTestPeriod -> 0, initialPoolSize -> 3, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, nestedDataSource -> com.mchange.v2.c3p0.DriverManagerDataSource@c16c6c30 [ description -> null, driverClass -> null, factoryClassLocation -> null, forceUseNamedDriverClass -> false, identityToken -> 1hgegw1a51wjuzuf1yrleln|11acdc30, jdbcUrl -> jdbc:mysql://localhost:3306/jpa, properties -> {user=******, password=******} ], preferredTestQuery -> null, privilegeSpawnedThreads -> false, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, usesTraditionalReflectiveProxies -> false; userOverrides: {} ], dataSourceName -> null, extensions -> {}, factoryClassLocation -> null, identityToken -> 1hgegw1a51wjuzuf1yrleln|21a5fd96, numHelperThreads -> 3 ] 527
2019-10-23 13:22:32 WARN com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@21e4631c -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (30). Last acquisition attempt exception:  1911
java.sql.SQLException: Unknown character set index for field '255' received from server.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:910)
	at com.mysql.jdbc.Connection.getCharsetNameForIndex(Connection.java:3448)
	at com.mysql.jdbc.Field.<init>(Field.java:191)
	at com.mysql.jdbc.MysqlIO.unpackField(MysqlIO.java:659)
	at com.mysql.jdbc.MysqlIO.getResultSet(MysqlIO.java:382)
	at com.mysql.jdbc.MysqlIO.readResultsForQueryOrUpdate(MysqlIO.java:1970)
	at com.mysql.jdbc.MysqlIO.readAllResults(MysqlIO.java:1387)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1727)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3170)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3099)
	at com.mysql.jdbc.Statement.executeQuery(Statement.java:1169)
	at com.mysql.jdbc.Connection.loadServerVariables(Connection.java:4317)
	at com.mysql.jdbc.Connection.initializePropsFromServer(Connection.java:3936)
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2683)
	at com.mysql.jdbc.Connection.<init>(Connection.java:1531)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:266)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1138)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1125)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
	at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1870)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
2019-10-23 13:22:32 WARN com.mchange.v2.resourcepool.BasicResourcePool Having failed to acquire a resource, com.mchange.v2.resourcepool.BasicResourcePool@7db0565c is interrupting all Threads waiting on a resource to check out. Will try again in response to new client requests. 946
2019-10-23 13:22:32 WARN org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator HHH000342: Could not obtain connection to query metadata : Connections could not be acquired from the underlying database! 132
2019-10-23 13:26:54 INFO org.hibernate.jpa.internal.util.LogHelper HHH000204: Processing PersistenceUnitInfo [
	name: myJpa
	...] 31
2019-10-23 13:26:56 INFO org.hibernate.Version HHH000412: Hibernate Core {5.4.0.Final} 46
2019-10-23 13:26:56 INFO org.hibernate.cfg.Environment HHH000206: hibernate.properties not found 199
2019-10-23 13:27:00 INFO org.hibernate.annotations.common.reflection.java.JavaReflectionManager HCANN000001: Hibernate Commons Annotations {5.1.0.Final} 49
2019-10-23 13:27:03 INFO org.hibernate.c3p0.internal.C3P0ConnectionProvider HHH010002: C3P0 using driver: com.mysql.jdbc.Driver at URL: jdbc:mysql://localhost:3306/jpa 116
2019-10-23 13:27:03 INFO org.hibernate.c3p0.internal.C3P0ConnectionProvider HHH10001001: Connection properties: {user=root, password=****} 117
2019-10-23 13:27:03 INFO org.hibernate.c3p0.internal.C3P0ConnectionProvider HHH10001003: Autocommit mode: false 120
2019-10-23 13:27:04 INFO com.mchange.v2.log.MLog$1 MLog clients using log4j logging. 124
2019-10-23 13:27:05 INFO com.mchange.v2.c3p0.C3P0Registry Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10] 248
2019-10-23 13:27:05 INFO org.hibernate.c3p0.internal.C3P0ConnectionProvider HHH10001007: JDBC isolation level: <unknown> 200
2019-10-23 13:27:05 INFO com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource Initializing c3p0 pool... com.mchange.v2.c3p0.PoolBackedDataSource@b80ba974 [ connectionPoolDataSource -> com.mchange.v2.c3p0.WrapperConnectionPoolDataSource@23f704de [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, debugUnreturnedConnectionStackTraces -> false, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, identityToken -> 1hgegw1a51wk1hjqclqsa|54afd745, idleConnectionTestPeriod -> 0, initialPoolSize -> 3, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, nestedDataSource -> com.mchange.v2.c3p0.DriverManagerDataSource@859df110 [ description -> null, driverClass -> null, factoryClassLocation -> null, forceUseNamedDriverClass -> false, identityToken -> 1hgegw1a51wk1hjqclqsa|4a8ab068, jdbcUrl -> jdbc:mysql://localhost:3306/jpa, properties -> {user=******, password=******} ], preferredTestQuery -> null, privilegeSpawnedThreads -> false, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, usesTraditionalReflectiveProxies -> false; userOverrides: {} ], dataSourceName -> null, extensions -> {}, factoryClassLocation -> null, identityToken -> 1hgegw1a51wk1hjqclqsa|5c77053b, numHelperThreads -> 3 ] 527
2019-10-23 13:27:36 WARN com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@8dfa7a9 -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (30). Last acquisition attempt exception:  1911
java.sql.SQLException: Unknown character set index for field '255' received from server.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:910)
	at com.mysql.jdbc.Connection.getCharsetNameForIndex(Connection.java:3448)
	at com.mysql.jdbc.Field.<init>(Field.java:191)
	at com.mysql.jdbc.MysqlIO.unpackField(MysqlIO.java:659)
	at com.mysql.jdbc.MysqlIO.getResultSet(MysqlIO.java:382)
	at com.mysql.jdbc.MysqlIO.readResultsForQueryOrUpdate(MysqlIO.java:1970)
	at com.mysql.jdbc.MysqlIO.readAllResults(MysqlIO.java:1387)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1727)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3170)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3099)
	at com.mysql.jdbc.Statement.executeQuery(Statement.java:1169)
	at com.mysql.jdbc.Connection.loadServerVariables(Connection.java:4317)
	at com.mysql.jdbc.Connection.initializePropsFromServer(Connection.java:3936)
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2683)
	at com.mysql.jdbc.Connection.<init>(Connection.java:1531)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:266)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1138)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1125)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
	at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1870)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
2019-10-23 13:27:36 WARN com.mchange.v2.resourcepool.BasicResourcePool Having failed to acquire a resource, com.mchange.v2.resourcepool.BasicResourcePool@52eacb4b is interrupting all Threads waiting on a resource to check out. Will try again in response to new client requests. 946
2019-10-23 13:27:36 WARN org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator HHH000342: Could not obtain connection to query metadata : Connections could not be acquired from the underlying database! 132
2019-10-23 13:30:41 INFO org.hibernate.jpa.internal.util.LogHelper HHH000204: Processing PersistenceUnitInfo [
	name: myJpa
	...] 31
2019-10-23 13:30:41 INFO org.hibernate.Version HHH000412: Hibernate Core {5.4.0.Final} 46
2019-10-23 13:30:41 INFO org.hibernate.cfg.Environment HHH000206: hibernate.properties not found 199
2019-10-23 13:30:42 INFO org.hibernate.annotations.common.reflection.java.JavaReflectionManager HCANN000001: Hibernate Commons Annotations {5.1.0.Final} 49
2019-10-23 13:30:42 INFO org.hibernate.c3p0.internal.C3P0ConnectionProvider HHH010002: C3P0 using driver: com.mysql.jdbc.Driver at URL: jdbc:mysql://localhost:3306/jpa 116
2019-10-23 13:30:42 INFO org.hibernate.c3p0.internal.C3P0ConnectionProvider HHH10001001: Connection properties: {user=root, password=****} 117
2019-10-23 13:30:42 INFO org.hibernate.c3p0.internal.C3P0ConnectionProvider HHH10001003: Autocommit mode: false 120
2019-10-23 13:30:43 INFO com.mchange.v2.log.MLog$1 MLog clients using log4j logging. 124
2019-10-23 13:30:43 INFO com.mchange.v2.c3p0.C3P0Registry Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10] 248
2019-10-23 13:30:43 INFO org.hibernate.c3p0.internal.C3P0ConnectionProvider HHH10001007: JDBC isolation level: <unknown> 200
2019-10-23 13:30:43 INFO com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource Initializing c3p0 pool... com.mchange.v2.c3p0.PoolBackedDataSource@47f01f66 [ connectionPoolDataSource -> com.mchange.v2.c3p0.WrapperConnectionPoolDataSource@58377e1a [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, debugUnreturnedConnectionStackTraces -> false, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, identityToken -> 1hgegw1a51wk6659zto5j0|6caf0677, idleConnectionTestPeriod -> 0, initialPoolSize -> 3, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, nestedDataSource -> com.mchange.v2.c3p0.DriverManagerDataSource@14482d53 [ description -> null, driverClass -> null, factoryClassLocation -> null, forceUseNamedDriverClass -> false, identityToken -> 1hgegw1a51wk6659zto5j0|51c668e3, jdbcUrl -> jdbc:mysql://localhost:3306/jpa, properties -> {user=******, password=******} ], preferredTestQuery -> null, privilegeSpawnedThreads -> false, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, usesTraditionalReflectiveProxies -> false; userOverrides: {} ], dataSourceName -> null, extensions -> {}, factoryClassLocation -> null, identityToken -> 1hgegw1a51wk6659zto5j0|5b247367, numHelperThreads -> 3 ] 527
2019-10-23 13:30:50 INFO org.hibernate.dialect.Dialect HHH000400: Using dialect: org.hibernate.dialect.MySQL8Dialect 158
2019-10-23 13:31:01 INFO org.hibernate.resource.transaction.backend.jdbc.internal.DdlTransactionIsolatorNonJtaImpl HHH10001501: Connection obtained from JdbcConnectionAccess [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess@74518890] for (non-JTA) DDL execution was not in auto-commit mode; the Connection 'local transaction' will be committed and the Connection will be set into auto-commit mode. 47
2019-10-23 13:31:02 INFO org.hibernate.resource.transaction.backend.jdbc.internal.DdlTransactionIsolatorNonJtaImpl HHH10001501: Connection obtained from JdbcConnectionAccess [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess@38600b] for (non-JTA) DDL execution was not in auto-commit mode; the Connection 'local transaction' will be committed and the Connection will be set into auto-commit mode. 47
2019-10-23 13:31:07 INFO org.hibernate.tool.schema.internal.SchemaCreatorImpl HHH000476: Executing import script 'org.hibernate.tool.schema.internal.exec.ScriptSourceInputNonExistentImpl@4e406694' 493
2019-10-23 13:31:07 INFO org.hibernate.engine.transaction.jta.platform.internal.JtaPlatformInitiator HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform] 52
